### PR TITLE
Add dependency into vendor dir.

### PR DESCRIPTION
**Pull request by StevenYCChou**
The current e2e-test doesn't have locked down dependency, so it needs to look up package under `GOPATH` or `GOROOT`. I also encountered an issue that I cannot `go get -u golang.org/x/net/context/ctxhttp`.

This PR is to add packages under vendor/, so the developer can always run the test without compilation error.

### CODE REVIEW

**Review by jkohen — APPROVED** [review]

**Comment by jkohen** [comment]
> I also encountered an issue that I cannot `go get -u golang.org/x/net/context/ctxhttp`.

Is this something we need to fix? I'm holding off on merging the PR until I understand that detail.

**Comment by StevenYCChou** [comment]
On current master branch, if I does `make`:
```
 % make        
go test ./... -args -integration -cluster-location=us-east1-c -cluster-name=REDACATED -namespace-name=REDACTED -project-id=REDACATED
stackdriver.go:23:2: cannot find package "google.golang.org/api/monitoring/v3" in any of:
        /usr/lib/google-golang/src/google.golang.org/api/monitoring/v3 (from $GOROOT)
        /usr/local/google/home/ycchou/go/src/google.golang.org/api/monitoring/v3 (from $GOPATH)
Makefile:17: recipe for target 'test-integration' failed
make: *** [test-integration] Error 1
```

with  dependency in vendor, any user wants to run the script can compile; it also always test with the same set of dependency.

**Comment by jkohen** [comment]
I think you're explaining the reason for this PR, which I agree with.

My question is about the specific sentence that I quoted. I still don't understand that.

**Comment by StevenYCChou** [comment]
I see what you meant. I don't think it's the scope of this PR as it's only related to `go get` command and whether `golang.org/x/net/context/ctxhttp` is downloadable.

However, I think passing what I saw will be valuable:
```
% go get -v -u golang.org/x/net/context/ctxhttp
Fetching https://golang.org/x/net/context/ctxhttp?go-get=1
Parsing meta tags from https://golang.org/x/net/context/ctxhttp?go-get=1 (status code 200)
get "golang.org/x/net/context/ctxhttp": found meta tag get.metaImport{Prefix:"golang.org/x/net", VCS:"git", RepoRoot:"https://go.googlesource.com/net"} at https://golang.org/x/net/context/ctxhttp?go-get=1
get "golang.org/x/net/context/ctxhttp": verifying non-authoritative meta tag
Fetching https://golang.org/x/net?go-get=1
Parsing meta tags from https://golang.org/x/net?go-get=1 (status code 200)
golang.org/x/net (download)
package golang.org/x/net/context/ctxhttp: cannot find package "golang.org/x/net/context/ctxhttp" in any of:
        /usr/lib/google-golang/src/golang.org/x/net/context/ctxhttp (from $GOROOT)
        /usr/local/google/home/ycchou/go/src/golang.org/x/net/context/ctxhttp (from $GOPATH)
```

because of this, I cannot run `go get` to get dependent package for compilation.

**Comment by jkohen** [comment]
Can you fix that dependency?

**Comment by StevenYCChou** [comment]
I don't think I can fix the dependency inside this repo. This repo uses golang.org/x/oauth2/google. That ctxhttp package is used inside golang.org/x/oauth2/google, and this codebase does not directly use ctxhttp.
```
 go get -u golang.org/x/oauth2/google 
package golang.org/x/net/context/ctxhttp: cannot find package "golang.org/x/net/context/ctxhttp" in any of:
        /usr/lib/google-golang/src/golang.org/x/net/context/ctxhttp (from $GOROOT)
        /usr/local/google/home/ycchou/go/src/golang.org/x/net/context/ctxhttp (from $GOPATH)
```

**Comment by jkohen** [comment]
Huh, that's bad, but thanks  for checking. I suggest reaching out to the maintainers.

**Pull request merged**
